[package]
name = "maze"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.16", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
pollster = "0.3"
rand = "0.8"
wgpu = "22.0"
winit = "0.29"
